package com.iot.riff.service.impl;

import com.iot.riff.service.IotDeviceDataService;
import com.iot.riff.service.dal.mongo.IotDeviceDal;
import com.iot.riff.service.dal.mongo.IotDeviceDataDal;
import com.iot.riff.service.dal.mongo.IotDeviceModelDal;
import com.iot.riff.service.domain.DeviceData;
import com.iot.riff.service.domain.IotDevice;
import com.iot.riff.service.domain.IotDeviceModel;
import com.iot.riff.service.util.IotJsonSchemaValidator;
import com.networknt.schema.ValidationMessage;
import io.micronaut.serde.ObjectMapper;
import jakarta.inject.Singleton;
import lombok.extern.slf4j.Slf4j;

import java.time.Instant;
import java.util.Map;
import java.util.Set;

@Slf4j
@Singleton
public class IotDeviceDataServiceImpl implements IotDeviceDataService {

    private final IotDeviceDataDal iotDeviceDataDal;
    private final IotDeviceDal iotDeviceDal;
    private final IotDeviceModelDal iotDeviceModelDal;
    private final IotJsonSchemaValidator iotJsonSchemaValidator;
    private final ObjectMapper objectMapper;

    public IotDeviceDataServiceImpl(IotDeviceDataDal iotDeviceDataDal,
            IotDeviceDal iotDeviceDal,
            IotDeviceModelDal iotDeviceModelDal,
            IotJsonSchemaValidator iotJsonSchemaValidator,
            ObjectMapper objectMapper) {
        this.iotDeviceDataDal = iotDeviceDataDal;
        this.iotDeviceDal = iotDeviceDal;
        this.iotDeviceModelDal = iotDeviceModelDal;
        this.iotJsonSchemaValidator = iotJsonSchemaValidator;
        this.objectMapper = objectMapper;
    }

    @Override
    public void processTelemetry(String deviceId, Map<String, Object> telemetryPayload) {
        // Fetch Device
        IotDevice device = iotDeviceDal.get(deviceId);
        if (device == null) {
            log.error("Device not found: {}", deviceId);
            return;
        }

        // Fetch Device Model
        IotDeviceModel deviceModel = iotDeviceModelDal.get(device.iotDeviceModelId().id());
        if (deviceModel == null) {
            log.error("Device Model not found for device: {}", deviceId);
            return;
        }

        // Validate Payload against Schema
        try {
            String payloadJson = objectMapper.writeValueAsString(telemetryPayload);
            Map<String, Object> schemaMap = deviceModel.telemetrySchema();
            if (schemaMap != null && !schemaMap.isEmpty()) {
                String schemaJson = objectMapper.writeValueAsString(schemaMap);
                Set<ValidationMessage> validationMessages = iotJsonSchemaValidator.validate(payloadJson, schemaJson);
                if (!validationMessages.isEmpty()) {
                    log.error("Payload validation failed for device {}: {}", deviceId, validationMessages);
                    return; // Drop message
                }
            }
        } catch (Exception e) {
            log.error("Error validating payload for device: {}", deviceId, e);
            return;
        }

        DeviceData deviceData = new DeviceData(
                null, // ID generated by DB
                deviceId,
                telemetryPayload,
                Instant.now() // received_at
        );

        iotDeviceDataDal.save(deviceData);
        log.info("Saved device data for device: {}", deviceId);
    }

    @Override
    public java.util.List<DeviceData> searchData(String deviceId, java.time.Instant start, java.time.Instant end,
            int limit, int page) {
        log.info("Searching device data for device: {}, range: [{}, {}], limit: {}, page: {}", deviceId, start, end,
                limit, page);
        return iotDeviceDataDal.findByDeviceIdAndTimeRange(deviceId, start, end, limit, page);
    }
}
